### ISSUE TITLE
Use https override for base map tiles

### ISSUE THREAD

**Issue by bradh** [ngageoint/opensphere-electron#1] opened 2018-03-12 19:33 UTC
From discussion:

> On a different issue - I saw some weirdness on electron, where it looked like it wanted to load base map tiles from `file://arcgis.blah/...`
> 
> Instead of `http/https://`

> 
> Oh, we’ll have to override the config for those. The config URL’s are using `//arcgis...` instead of specifying HTTP or HTTPS, so it uses the same scheme as the application.
> 
> But with Electron, the application scheme is `file://` :confused:
> 
> The current config is matching the app scheme for CORS reasons.

**Comment by schmidtk** [comment] 2018-03-13 18:45
Closed via ngageoint/opensphere-config-electron/issues/1.

**Closed by schmidtk** 2018-03-13 18:45 UTC

**Comment by schmidtk** [comment] 2018-03-13 18:50
I replaced the offending config in `opensphere-config-electron`, but we may still want to look into a long term/generic solution if we detect the app is using the `file` protocol. Part of the problem is that we don't run all requests through the `os.net` stack (tiles, for example). We could preprocess the config when starting up Electron, but I'm a little wary of doing that.
